### ISSUE TITLE
Question: why google analytics instead of other more privacy friendly web analytics tool?

### ISSUE THREAD

**Issue by vrde** [attestate/kiwistand#25]
I noticed that kiwistand implements Google Analytics. Out there there are more privacy friendly tools, one of them (that you know very well) is plausible.io. Why not using it instead of GA?

**Comment by TimDaub** [comment]
yeah fair question:

For a social app to scale, it‘s important to be aware of:

- DAU / WAU percentage (indicates how often returning users are coming back to use the app)
- Retention stats (are prior users coming back to the site)
- other similar metrics, for an idea see: https://a16z.com/2020/12/07/social-strikes-back-fastest-growing-apps/

The problem with plausible is that it fundamentally doesn‘t correlate between two sessions of any user, which means that those values aren‘t available (e.g. DAU value cannot be computed and eg session time is an average)

I understand the privacy concerns around GA and it also forces us to implement an ugly banner. But for understanding traffic, I found it quite useful for the last few days. 

With rugpullindex.com I ended up using plausible and in the end it created problems because it didn‘t track some 6 months of DAU data e.g. that would have made grants funding easier to motivate.

Additionally, the social space is extremely competitive and we‘re literally competing with the biggest companies in the world for eye balls, essentially.

I guess if I wanted to raise money (which I‘m not sure about), then those metrics probably translate into dollars…

Now, I‘d be open to switching to a tool that isn‘t GA but analyzes key metrics of a social app (maybe there is a self-hosted one). But it‘d mean that we have to do a thorough job in understanding which metrics to track and which tool. GA does that currently out of the box.

Curious to here ur thoughts here, maybe u know a good tool. I figure eg the privacy issue would less concerning if we had a self-hosted tool?

**Comment by TimDaub** [comment]
- kiwinews.xyz will remain using tracking as it has turned out to be instrumental in growing the product.
- However, @freeatnet has added RSS feeds to his frontend, which are much harder to track users on

>RSS feeds are now on the main URL and display points, submitter, upvoters: https://kiwinews-webapp.vercel.app/api/feed/new and https://kiwinews-webapp.vercel.app/api/feed/feed 

They're also hosting https://kiwinews-webapp.vercel.app/, which is an alternative frontend and may have different policies towards tracking.

Additionally, anyone can run Kiwi News, and the Google Analytics files (https://github.com/attestate/kiwistand/blob/main/src/public/ga.js) can be deleted when running a separate node. Closing

**Comment by TimDaub** [comment]
Still not perfect, but you can now go to https://news.kiwistand.com?anon on e.g. a private tab and it'll auto-log into an ephemeral Ethereum wallet.

Privacy Enhancements in Anon Mode:

- Tracking Scripts: Disabled Google Analytics, PostHog tracking
- User Behavior Tracking: Disabled link impression tracking, interaction tracking, outbound link tracking, and share tracking beacons
- External Resources: Self-hosted Inter font (eliminated Google Fonts tracking) and created favicon proxy endpoint (eliminated Google favicon tracking)
- Image Privacy: Prevented external image loads to block third-party tracking via images
- Network Restrictions: Limited RPC chains to Optimism and Mainnet only
- UI/UX: Added anon mode login option, disabled page reordering to prevent flash, and created subtle dark mode theme

Please do your own research to see what other routines leak data. I will fix it if you report. Some known issues:

- Kiwi images are hosted on CF
- CF still inserts their analytics script
- I may have overlooked certain things
- Obviously you are leaking data to my server. You are, of course, free to run your own instance of Kiwi News.

Certain wallets may still compromise our privacy too. This is because how wallets are inserted via JS is not ideal. But I think if you go via ?anon then you should be mostly safe. I have filed issues with those who I saw requests:

- https://github.com/rainbow-me/rainbowkit/issues/2560
- https://github.com/ithacaxyz/porto/issues/1027
- https://github.com/reown-com/appkit/issues/5328
- https://github.com/coinbase/coinbase-wallet-sdk/issues/1808

Anyways, the goal was here to minimize where data was being spread and so if you're concerned for your privacy then this should be a pretty significant improvement.

In anon mode you can post as usual. Meaning you can comment, upvote, submit, emoji-react. The only difference to logged-in mode is that every time you load a new session a fresh Ethereum private key is generated that then gets discarded later. Which means no persistent identity is possible in anon mode. You'll always just be a newly-generated random Ethereum address.

Don't bet the farm yet on being anon. This is an early alpha.

I hope some people will appreciate this. Privacy is normal.

Will send out a blog post and market this more broadly later.

PS: As for picking your own RPC endpoints. I did consider this but actually I didn't see any RPC calls anymore in anon mode so for now I didn't care.
